apiVersion: v1
kind: Service
metadata:
  name: addagendaservice-service
spec:
  type: ClusterIP
  selector:
    app: addagendaservice
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001